### PR TITLE
Automate release with github workflow

### PR DESCRIPTION
**Pull request by hmasum52**
### Step by step guide

> [!WARNING]  
> Make sure your `versionName` in `app/build.gradle.kts` is updated before pushing anything to master to create a release.

1. Convert Keystore File to Base64 Convert your keystore.jks file to a base64 string using the following command
```
cat keystore.jks | base64 > keystore.jks.base64
```
copy the content of `keystore.jks.base64`. 

2. Go to your repository’s settings, navigate to `Secrets and variables” > Actions`, and add the following secrets:
- `KEYSTORE_BASE64`: The content of `keystore.jks.base64`.
- `KEYSTORE_PASSWORD`: The password for your keystore.
- `KEY_ALIAS`: The alias for your key.
- `KEY_PASSWORD`: The password for your key alias.  

image

Here is a snapshot from my repository. 

image

This actions will create a release. 

image

You will also find the artifacts in the actions as well

image

### CODE REVIEW

**Comment by aniruddha-adhikary** [comment]
This is amazing! Thank for all the effort @hmasum52 :D Appreciate every bit of this. I think my last push created some conflicts. Yikes.

**Comment by hmasum52** [comment]
@aniruddha-adhikary I think I have resolved the conflicts. Please follow the steps mentioned in the PR to add the secrets before merging to master branch! Also consider working in a separate branch & make PRs as the workflow will trigger every time there is a push on master branch. 

If you want to manually trigger the workflow then just comment out the the following in the workflow file
```
on:
  # push:
  #  branches: [ master ]

  workflow_dispatch: # Manually trigger the workflow
 ```
 Let me know if you need any help!

**Comment by aniruddha-adhikary** [comment]
hmm looks like the merge conflict is still an issue. Say what, let me cherry pick your commits and apply them.

**Comment by hmasum52** [comment]
@aniruddha-adhikary I have merged the current master in my recent commits. There shouldn't be any conflicts anymore!

**Comment by aniruddha-adhikary** [comment]
Hands down this is one of the best Pull Requests I have seen in my life as a Software Engineer. The amount of detail and instruction that went into crafting the description --- left me speechless.

I can only thank you for this.

**Pull request merged**
