### PR TITLE
fix: Station Names

### PR DESCRIPTION
**Pull request by kazimmt**

### CODE REVIEW

**Comment by aniruddha-adhikary** [comment]
@kazimmt thanks for the contribution! Are you sure about the codes of Secretariat and DU? Just double checking.

**Comment by kazimmt** [comment]
I'm sure
I've visited these places multiple times

**Comment by aniruddha-adhikary** [comment]
Oh no, the commits disappeared!

**Comment by kazimmt** [comment]
I revert the commit bcz of conflicts (made by your last commit xD)

**Review by aniruddha-adhikary — APPROVED** [review]
Looks good! Thank you for adding the names in!

**Pull request merged**
