### PR TITLE
Refactor ui - balance card 

### PR DESCRIPTION
**Pull request by itsPronay**
## Refactored Balance Card - 

Note:  the balance display for the `showBalance` feature has not been modified .

Here are some images 
<p>
  Balance Card Image 1
  Balance Card Image 2
  Balance Card Image 3

</p>

<p>
  Balance Card Image 4
  Balance Card Image 5
  
</p>

### CODE REVIEW

**Comment by aniruddha-adhikary** [comment]
This looks amazing @itsPronay 

Could we get the source of the images and their licensing terms - just to make sure we're not violating any copyright.

**Comment by kazimmt** [comment]
@aniruddha-adhikary Can we change the word "Tap"
As we're not tapping actually!

**Comment by kazimmt** [comment]
> Could we get the source of the images
https://www.freepik.com/icon/money_11060039

**Comment by kazimmt** [comment]
image

**Review by kazimmt — CHANGES_REQUESTED** [review]
The wireless icon has slightly problem,,,
Specially in dark mode
image

**Comment by itsPronay** [comment]
@kazimmt I'll fix that

**Review by kazimmt — APPROVED** [review]

**Comment by aniruddha-adhikary** [comment]
nitpick: The last error message appears to be a computer, could we make it a mobile phone instead?

**Comment by itsPronay** [comment]
@aniruddha-adhikary sure, will change that

**Comment by itsPronay** [comment]
@aniruddha-adhikary see if you like this one instead
image

**Comment by aniruddha-adhikary** [comment]
I ran your changes! Thank you so much for your contribution. But looks like the table of transaction history is missing now.

**Comment by itsPronay** [comment]
@aniruddha-adhikary, could you tell me for which UI state in the history table is missing? I don't have a metro card, so I'm unable to check it myself.

**Pull request closed without merging**
