### PR TITLE
Dark Mode for website #62

### PR DESCRIPTION
**Pull request by anikbsmrstucse**
Implement Dark Mode in whole landing page using context API

- implement dark mode helps with tailwind css
- it's working for all pages
- And it's switch dark and light mode using system preferences
- Add Icon in navbar when switch theme icon will be sun or moon

N:B: I am using prettier formator that's why some change in whole file(sorry for that)

### CODE REVIEW

**Comment by aniruddha-adhikary** [comment]
Do you want to add the prettier rc file?

**Comment by anikbsmrstucse** [comment]
No sir thank you, my prettier is configure globally and i don't know my prettier rc config.

**Comment by aniruddha-adhikary** [comment]
Thank you so much @anikbsmrstucse ! Appreciate your contribution!

**Comment by anikbsmrstucse** [comment]
You are welcome sir❤

**Pull request merged**
